cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_cart, name='show_cart'),    
    path('update_cart/', views.update_cart, name='update_cart'),
    path('delete_from_main_cart/', views.delete_from_main_cart, name='delete_from_main_cart'),
    path('use_promo/', views.use_promo, name='use_promo'),
    path('sort_filter/', views.sort_filter, name='sort_filter'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('delete_from_cart/', views.delete_from_cart, name='delete_from_cart'),
    path('wishlist_add/', views.wishlist_add, name='wishlist_add'),
    path('wishlist_delete/', views.wishlist_delete, name='wishlist_delete'),


]

item/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('quick_add_to_cart/', views.quick_add_to_cart, name='quick_add_to_cart'),
#    path('<item_slug>/', views.item_page, name='item_page'),


]

khimiya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static


from page.views import customhandler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('item/', include('item.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('customuser.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = customhandler404

cart/models.py
from django.db import models
from customuser.models import User, Guest
from item.models import ItemPrice

class Cart(models.Model):
    client = models.ForeignKey(User, blank=True, null=True, default=None, on_delete=models.CASCADE,
                               verbose_name='Корзина клиента')
    guest = models.ForeignKey(Guest, blank=True, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='Корзина гостя')
    item = models.ForeignKey(ItemPrice, blank=True, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='Товар')
    number = models.IntegerField('Кол-во', blank=True, null=True, default=0)
    current_price = models.IntegerField('Цена за текущий товар', default=0)
    total_price = models.IntegerField('Общая стоимость', default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.client:
            return 'Товар в корзине клиента : %s ' % self.client.name
        elif self.guest:
            return 'Товар в корзине гостя : %s ' % self.guest.id
        else:
            return 'Товар в корзине'

    class Meta:
        verbose_name = "Товар в корзине"
        verbose_name_plural = "Товары в корзинах"

    def save(self, *args, **kwargs):
        if self.item.discount > 0:
            self.current_price = (self.item.price - (self.item.price * self.item.discount / 100)) * self.number
        else:
            self.current_price = self.item.price
        self.total_price = self.number * self.current_price
        super(Cart, self).save(*args, **kwargs)

order/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from customuser.models import User, Guest
from item.models import Item, ItemPrice, PromoCode
from django.utils.safestring import mark_safe

class Wishlist(models.Model):
    client = models.ForeignKey(User, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                               verbose_name='Клиент')
    item = models.ForeignKey(Item, blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Товар')

    def __str__(self):
        return 'Избранный товар : %s ' % self.client.email

    class Meta:
        verbose_name = "Избранный товар"
        verbose_name_plural = "Избранные товары"


class OrderStatus(models.Model):
    name = models.CharField('Статус для заказа', max_length=100, blank=False)
    def __str__(self):
        return '%s' % self.name
    class Meta:
        verbose_name = "Статус для заказа"
        verbose_name_plural = "Статусы для заказов"

class OrderPayment(models.Model):
    name = models.CharField('Вариант оплаты заказа', max_length=100, blank=False)
    def __str__(self):
        return '%s' % self.name
    class Meta:
        verbose_name = "Вариант оплаты заказа"
        verbose_name_plural = "Варианты оплаты заказов"

class OrderShipping(models.Model):
    name = models.CharField('Вариант доставки заказа', max_length=100, blank=False)
    deliveryCost = models.IntegerField('Стоимость доставки', default=0)
    def __str__(self):
        return '%s' % self.name
    class Meta:
        verbose_name = "Вариант доставки заказа"
        verbose_name_plural = "Варианты доставки заказов"

class Order(models.Model):
    client = models.ForeignKey(User, blank=True, null=True, default=None, on_delete=models.CASCADE,
                               verbose_name='Заказ клиента')
    guest = models.ForeignKey(Guest, blank=True, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='Заказ гостя')
    promo_code = models.ForeignKey(PromoCode, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                              verbose_name='Использованный промо-код')
    status = models.ForeignKey(OrderStatus, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                              verbose_name='Статус заказа')
    payment = models.ForeignKey(OrderPayment, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                               verbose_name='Оплата заказа')
    shipping = models.ForeignKey(OrderShipping, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                                verbose_name='Доставка заказа')
    total_price = models.IntegerField('Общая стоимость заказа', default=0)
    total_price_with_code = models.IntegerField('Общая стоимость заказа с учетом промо-кода', default=0)
    bonuses = models.IntegerField('Бонус с заказа', blank=True, default=0, db_index=True)
    track_code = models.CharField('Трек код', max_length=50, blank=True, null=True)
    order_code = models.CharField('Код заказа', max_length=10, blank=True, null=True)
    is_complete = models.BooleanField('Заказ выполнен ?', default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):

        if self.client:
            if self.promo_code:
                return 'Заказ № %s. Создан : %s  . Клиент: %s . Сумма заказа : %s' % (
                self.id, self.created_at.strftime('%d-%m-%Y'), self.client.email, self.total_price_with_code)
            else:
                return 'Заказ № %s. Создан : %s  . Клиент: %s . Сумма заказа : %s' % (
                self.id, self.created_at.strftime('%d-%m-%Y'), self.client.email, self.total_price)
        if self.guest:
            if self.promo_code:
                return 'Заказ № %s. Создан : %s  . Гость: %s . Сумма заказа : %s' % (
                self.id, self.created_at.strftime('%d-%m-%Y'), self.guest.email, self.total_price_with_code)
            else:
                return 'Заказ № %s. Создан : %s  . Гость: %s . Сумма заказа : %s' % (
                self.id, self.created_at.strftime('%d-%m-%Y'), self.guest.email, self.total_price)


    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def created_tag(self):

        return mark_safe('<strong>{}</strong>'.format(self.created_at.strftime('%d-%m-%Y, %H:%M:%S')))

    created_tag.short_description = mark_safe('<strong>Дaта заказа</strong>')

    def save(self, *args, **kwargs):
        if self.promo_code:
            self.total_price_with_code = (self.total_price - (self.total_price * self.promo_code.promo_discount / 100)) - self.bonuses
        else:
            self.total_price_with_code = self.total_price - self.bonuses
        super(Order, self).save(*args, **kwargs)

class ItemsInOrder(models.Model):
    order = models.ForeignKey(Order, blank=False, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='В заказе')
    item = models.ForeignKey(ItemPrice, blank=False, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='Товар')
    number = models.IntegerField('Кол-во', blank=True, null=True, default=0)
    total_price = models.IntegerField('Общая стоимость', default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.total_price = self.number * self.item.price
        super(ItemsInOrder, self).save(*args, **kwargs)


    def __str__(self):
        return 'Товар : %s . В заказе № %s .' % (self.item.item.name, self.order.id)

    class Meta:
        verbose_name = "Товар в заказе"
        verbose_name_plural = "Товары в заказе"

    def getfirstimage(self):
        url = None
        for img in self.item.item.itemimage_set.all():
            if img.is_main:
                url = img.image_small
        return url

    def image_tag(self):
        # used in the admin site model as a "thumbnail"
        if self.getfirstimage():
            return mark_safe('<img src="{}" width="100" height="100" />'.format(self.getfirstimage()))
        else:
            return mark_safe('<span>НЕТ МИНИАТЮРЫ</span>')

    def name_tag(self):
        name = self.item.item.name
        return name


    name_tag.short_description = 'Название товара'
    image_tag.short_description = 'Основная картинка'


def ItemsInOrder_post_save(sender,instance,**kwargs):
    try:
        order = instance.order
    except:
        order = None

    if order:
        order_total_price = 0
        all_items_in_order = ItemsInOrder.objects.filter(order=order)

        for item in all_items_in_order:
            order_total_price += item.total_price
        instance.order.total_price = order_total_price
        instance.order.save(force_update=True)


post_delete.connect(ItemsInOrder_post_save, sender=ItemsInOrder)
post_save.connect(ItemsInOrder_post_save, sender=ItemsInOrder)

item/views.py
import decimal

from django.shortcuts import render
from django.http import JsonResponse, Http404
from item.models import Item,ItemPrice,ItemImage
from cart.models import Cart
from customuser.models import User, Guest

def quick_add_to_cart(request):
    return_dict = {}
    data = request.POST
    print(data)
    item_id = int(data.get('item_id'))
    item = Item.objects.get(id=item_id)
    images = ItemImage.objects.filter(item_id=item_id)
    volumes = ItemPrice.objects.filter(item=item)
    print(volumes)
    return_dict['item_id'] = item.id
    return_dict['item_name'] = item.name
    return_dict['item_name_slug'] = item.name_slug
    return_dict['item_description'] = item.description
    # return_dict['item_price'] = item.price
    return_dict['item_present'] = item.is_present

    return_dict['item_images'] = list()
    return_dict['item_volumes'] = list()

    for image in images:
        return_dict['item_images'].append(image.image_small)
    for vol in volumes:
        item_volume = dict()
        item_volume['id'] = vol.id
        item_volume['volume'] = vol.volume

        item_volume['price'] = vol.price
        if vol.discount > 0:
            item_volume['price_with_discount'] = vol.price_with_discount
        item_volume['unit'] = vol.unit

        return_dict['item_volumes'].append(item_volume)
    return JsonResponse(return_dict)




def item_page(request, item_slug):
    print(request.get_host())
    try:
        item = Item.objects.get(name_slug=item_slug)
        item.views += 1
        item.save(force_update=True)
        recomended = Item.objects.filter(subcategory_id=item.subcategory_id).order_by('-views')[:12]
        # title = item.name
        # description = item.description

        print(recomended)
    except:
        raise Http404
        # return render(request, '404.html', locals())
    title = '{} | артикул {} - купить оптом в Москве'.format(item.name, item.article)
    description = 'Заказывайте оптом {} (артикул {}) в интернет-магазине ЛАКШМИ.' \
                  ' Большой выбор товаров на различную тематику по доступным ценам. Доставка по России.'.format(item.name, item.article)
    return render(request, 'item/item.html', locals())

order/views.py
from django.shortcuts import render

# Create your views here.

templates/page/cart.html
{% extends 'basic.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    {% include 'header_grey.html' %}

    {% if total_cart_price %}
        <section class="item">
    <div class="container">
        <div class="breadcrumbs">
            <ul>
                <li><a href="#">Главная</a></li>
                <li><span>Корзина</span></li>
            </ul>
        </div>
        <div class="cart">
            <table class="main-cart-items">
                <thead class="main-cart-items-head">
                <tr>
                    <td>Товары</td>
                    <td>Кол-во</td>
                    <td>Цена</td>
                    <td>Сумма</td>
                    <td>Действие</td>
                </tr>
                </thead>
                <tbody id="cart_body">
                   {% for cart_item in all_items_in_cart %}
                <tr class="main-cart-item">
                    <td>
                        <div class="main-cart-item-name">
                            <img src="{{ cart_item.item.item.itemimage_set.first.image_small }}" alt=""> <span>{{ cart_item.item.item.name }} {{ cart_item.item.volume }} {{ cart_item.item.unit }}</span>
                        </div>

                    </td>
                    <td class="main-cart-item-number">
                        <div class="custom-input main-cart">
                            <button class="custom-input-minus" data-item_id="{{ cart_item.id }}" onclick="mainCartMinusItem(this)">-</button>
                            <input id="{{ cart_item.id }}_item_total" data-item_in_cart_id="{{ cart_item.id }}" value="{{ cart_item.number }}" disabled onchange="change_cart(this)">
                            <button class="custom-input-plus" data-item_id="{{ cart_item.id }}" onclick="mainCartPlusItem(this)">+</button>

                        </div>
                    </td>
                    <td class="main-cart-item-price">{{ cart_item.current_price}} &#8381;</td>
                    <td class="main-cart-item-total-price">{{ cart_item.total_price }} &#8381;</td>
                    <td class="main-cart-item-action"><a class="cart-delete-btn" onclick="delete_from_main_cart({{ cart_item.id }})" href="javascript:void(0)"><span>&#10006;</span></a></td>
                </tr>
                {% endfor %}
                <tr class="main-cart-footer">
                    <td class="main-cart-footer__total">Итого</td>
                    <td></td>
                    <td></td>
                    <td colspan="2" class="main-cart-footer__total-price">{{ total_cart_price }} &#8381;</td>

                </tr>

                </tbody>
            </table>

        </div>
     <div class="main-cart__buttons">
            <a href="javascript:history.go(-1);" class="btn-outline btn-md">продолжить покупки</a>
            <a href="{% url 'checkout' %}" class="btn btn-md">оформить заказ</a>
        </div>

    </div>
</section>
    <section class="relative-items">
    <div class="container">
        <h3>С этим товаром берут</h3>
        <div class="item-cards">
            <div class="item-card ">
                <div class="item-card-discount">
                    -15 %
                </div>

                <div class="item-card-favorite-btn">
                    <a href="#"><i class="favorite-icon"></i></a>
                </div>
                <div class="item-card-inner">
                    <a href="#"><img src="img/item.png" alt=""></a>

                    <a href="#"><p class="item-card-name">Lorem ipsum.</p></a>
                    <p class="item-card-description">Lorem ipsum dolor sit amet, consectetur.</p>
                </div>
                <div class="item-card-price">
                    <p> 1300 Р</p>
                </div>
            </div><!--item-card-->
            <div class="item-card ">
                <div class="item-card-discount">
                    -15 %
                </div>

                <div class="item-card-favorite-btn">
                    <a href="#"><i class="favorite-icon"></i></a>
                </div>
                <div class="item-card-inner">
                    <a href="#"><img src="img/item.png" alt=""></a>

                    <a href="#"><p class="item-card-name">Lorem ipsum.</p></a>
                    <p class="item-card-description">Lorem ipsum dolor sit amet, consectetur.</p>
                </div>
                <div class="item-card-price">
                    <p> 1300 Р</p>
                </div>
            </div><!--item-card-->
            <div class="item-card ">
                <div class="item-card-discount">
                    -15 %
                </div>

                <div class="item-card-favorite-btn">
                    <a href="#"><i class="favorite-icon"></i></a>
                </div>
                <div class="item-card-inner">
                    <a href="#"><img src="img/item.png" alt=""></a>

                    <a href="#"><p class="item-card-name">Lorem ipsum.</p></a>
                    <p class="item-card-description">Lorem ipsum dolor sit amet, consectetur.</p>
                </div>
                <div class="item-card-price">
                    <p> 1300 Р</p>
                </div>
            </div><!--item-card-->
            <div class="item-card ">
                <div class="item-card-discount">
                    -15 %
                </div>

                <div class="item-card-favorite-btn">
                    <a href="#"><i class="favorite-icon"></i></a>
                </div>
                <div class="item-card-inner">
                    <a href="#"><img src="img/item.png" alt=""></a>

                    <a href="#"><p class="item-card-name">Lorem ipsum.</p></a>
                    <p class="item-card-description">Lorem ipsum dolor sit amet, consectetur.</p>
                </div>
                <div class="item-card-price">
                    <p> 1300 Р</p>
                </div>
            </div><!--item-card-->
        </div>

    </div>

</section>
    {% else %}
        {% include 'page/empty_cart.html' %}
    {% endif %}




{% endblock %}

{% block js %}
    <script src="{% static 'js/jquery.showLoading.min.js' %}"></script>
    <script src="{% static 'js/cart.js' %}"></script>
    <script src="{% static 'js/delete_from_main_cart.js' %}"></script>

<script>
function mainCartPlusItem(el){
        let event = new Event('change');
        let item_id= el.dataset.item_id
        let id= item_id +'_item_total'

        let oldValue = document.getElementById(id).value


        let newVal = parseFloat(oldValue) + 1;

        document.getElementById(id).value = newVal
        document.getElementById(id).dispatchEvent(event);
    }

    function mainCartMinusItem(el){
        let event = new Event('change');
        let item_id= el.dataset.item_id
        let id= item_id +'_item_total'
        let oldValue = document.getElementById(id).value

        if (parseFloat(oldValue) > 2){
            var newVal = parseFloat(oldValue) - 1;

        }else {
            var newVal = 1
        }
        document.getElementById(id).value = newVal
        document.getElementById(id).dispatchEvent(event);
    }
</script>

{% endblock %}

templates/page/checkout.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}
    {% include 'header_grey.html' %}
    {% if total_cart_price %}
        {% if request.user.is_authenticated %}
            {% include 'page/checkout_members.html' %}
        {% else %}
            {% include 'page/checkout_guest.html' %}
        {% endif %}
    {% else %}
         {% include 'page/empty_cart.html' %}
    {% endif %}
{% endblock %}

templates/page/empty_cart.html
<div class="container">
<section style="margin: 100px 0; display: flex; flex-direction: column;align-items: center" class="empty_cart">
    <h1 style="color: #333333; margin-bottom: 30px;">Ваша корзина пуста</h1>
    <a href="/" class="btn">на гланую</a>


</section>
</div>

templates/page/item_card.html
{% load static %}
{% load mytags %}
<div class="item-card ">
    {{ item | is_discount |safe }}


    <div class="item-card-favorite-btn">
        <a href="#"><i class="favorite-icon"></i></a>
    </div>
    <div class="item-card-inner">
        <a href="{% url 'showitem' cat.name_slug subcategory.name_slug subsubcat.name_slug item.name_slug %}"> <img
                {% for image in item.itemimage_set.all %}
                    {% if image.is_main %}
                        src="{{ image.image_small }}" alt="">
                    {% endif %}
                {% endfor %}
        </a>
        <div class="item-card-info">
            <a href="#"><p class="item-card-name">{{ item.name }}</p></a>
            {% if item.short_description %}
                <p class="item-card-description">{{ item.short_description }}</p>
            {% endif %}
        </div>

    </div>
    <div class="item-card-price">
        {{ item | check_discount | safe}}


        <a class="btn " href="javascript:void(0)" onclick="quick_add_to_cart({{ item.id }})">в корзину</a>
        {% if request.user.is_authenticated and  request.user.is_staff%}
            <hr>
            <a href="/admin/item/item/{{ item.id }}/change/">редактировать</a>
        {% endif %}

    </div>
</div><!--item-card-->

templates/page/order.html
{% extends 'basic.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    {% include 'header_grey.html' %}

   <section class="order">
    <div class="container">
        <div class="breadcrumbs">
            <ul>
                <li><a href="/">Главная</a></li>
                <li><span>Ваш заказ</span></li>
            </ul>
        </div>
        <div class="order-inner">
            <h3>Спасибо за Ваш заказ.</h3>
            <div class="order-info">

             <p>Код заказа : <strong>{{ order.order_code }}</strong></p>
                <p>Статус заказа: <strong>{% if order.status %}{{ order.status.name }}{% else %}ОТПРАВЛЕН МЕНЕДЖЕРУ{% endif %}</strong></p>
            </div>





            <h3>Вы заказали:</h3>

              <div class="cart">
            <table class="main-cart-items">

                <tbody>
                {% for orderItem in order.itemsinorder_set.all %}
                <tr class="main-cart-item">
                    <td>
                        <div class="main-cart-item-name">
                            <img src="{{ orderItem.item.item.itemimage_set.first.image_small }}" alt="">
                            <span>{{ orderItem.item.item.name }} {{ orderItem.item.volume }} л</span>
                        </div>

                    </td>
                    <td class="main-cart-item-price">
                       {{ orderItem.number }} ед.
                    </td>
                    <td class="main-cart-item-price">{{ orderItem.item.price }} &#8381;</td>
                    <td class="main-cart-item-total-price">{{ orderItem.total_price }} &#8381;</td>
                </tr>
                {% endfor %}
                {% if order.bonuses or order.promo_code %}
                 <tr class="main-cart-footer">
                    <td class="main-cart-footer__total">Сумма заказа</td>
                    <td></td>
                    <td></td>
                    <td class="main-cart-footer__total-price">{{ order.total_price }} &#8381;</td>
                </tr>
                {% endif %}
                {% if order.promo_code %}
                 <tr class="main-cart-footer">
                    <td class="main-cart-footer__total">Скидка по промо-коду</td>
                    <td></td>
                    <td></td>
                    <td class="main-cart-footer__total-price">{{ order.promo_code.promo_discount }} %</td>
                </tr>
                {% endif %}
                {% if order.bonuses %}
                 <tr class="main-cart-footer">
                    <td class="main-cart-footer__total">Использовано бонусов</td>
                    <td></td>
                    <td></td>
                    <td class="main-cart-footer__total-price">{{ order.bonuses }} &#8381;</td>
                </tr>
                {% endif %}
                <tr class="main-cart-footer">
                    <td class="main-cart-footer__total">Итого</td>
                    <td></td>
                    <td></td>
                    <td class="main-cart-footer__total-price">{{ order.total_price_with_code }} &#8381;</td>

                </tr>

                </tbody>
            </table>

        </div>



        </div>


    </div>
</section>

{% endblock %}

{% block js %}
{% endblock %}