cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_cart, name='show_cart'),    
    path('update_cart/', views.update_cart, name='update_cart'),
    path('delete_from_main_cart/', views.delete_from_main_cart, name='delete_from_main_cart'),
    path('use_promo/', views.use_promo, name='use_promo'),
    path('sort_filter/', views.sort_filter, name='sort_filter'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('delete_from_cart/', views.delete_from_cart, name='delete_from_cart'),
    path('wishlist_add/', views.wishlist_add, name='wishlist_add'),
    path('wishlist_delete/', views.wishlist_delete, name='wishlist_delete'),


]

khimiya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static


from page.views import customhandler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('item/', include('item.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('customuser.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = customhandler404

item/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import Truncator
from pytils.translit import slugify
from PIL import Image
from django.db.models.signals import post_save, post_delete, pre_save
import uuid
from random import choices
import string
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.utils.safestring import mark_safe

import os

from khimiya.settings import BASE_DIR


def format_number(num):
    if num % 1 == 0:
        return int(num)
    else:
        return num


class Category(models.Model):
    name = models.CharField('Название категории', max_length=255, blank=False, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField('Изображение категории', upload_to='category_img/', blank=True)
    page_title = models.CharField('Название страницы SEO', max_length=255, blank=True, null=True)
    page_description = models.CharField('Описание страницы SEO', max_length=255, blank=True, null=True)
    page_keywords = models.TextField('Keywords SEO', blank=True, null=True)
    short_description = models.TextField('Краткое описание', blank=True)
    description = RichTextUploadingField('Описание категории', blank=True, null=True)
    views = models.IntegerField('Просмотров', default=0)
    is_active = models.BooleanField('Отображать категорию ?', default=True, db_index=True)
    cat_id = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return '%s ' % self.name

    class Meta:
        verbose_name = "Основная категория"
        verbose_name_plural = "Основные категории"


class SubCategory(models.Model):
    category = models.ForeignKey(Category, blank=False, null=True, on_delete=models.SET_NULL,verbose_name='Основная категория')
    name = models.CharField('Название подкатегории', max_length=255, blank=False, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField('Изображение подкатегории', upload_to='sub_category_img/', blank=True)
    page_title = models.CharField('Название страницы SEO', max_length=255, blank=True, null=True)
    page_description = models.CharField('Описание страницы SEO', max_length=255, blank=True, null=True)
    page_keywords = models.TextField('Keywords SEO', blank=True, null=True)
    description = RichTextUploadingField('Описание подкатегории', blank=True, null=True)
    short_description = models.TextField('Краткое описание', blank=True)
    discount = models.IntegerField('Скидка на все товары в подкатегории %', blank=True, default=0)
    views = models.IntegerField('Просмотров', default=0)
    is_active = models.BooleanField('Отображать подкатегорию ?', default=True, db_index=True)
    subcat_id = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        slug = slugify(self.name)
        print(slug)
        testSlug = SubCategory.objects.filter(name_slug=slug)
        print(testSlug)
        slugRandom = ''
        if not self.name_slug or testSlug:
            if testSlug:
                slugRandom = '-' + ''.join(choices(string.ascii_lowercase + string.digits, k=2))
                self.name_slug = slug + slugRandom
            else:
                self.name_slug = slug
        self.name_lower = self.name.lower()
        # all_items = self.item_set.all()
        # for item in all_items:
        #     item.discount = self.discount
        #     item.save()

        super(SubCategory, self).save(*args, **kwargs)

    def __str__(self):
        return '%s ' % self.name

    class Meta:
        verbose_name = "Основная подкатегория"
        verbose_name_plural = "Основные подкатегории"


class SubSubCategory(models.Model):
    subcategory = models.ForeignKey(SubCategory, blank=False, null=True, on_delete=models.SET_NULL,
                                    verbose_name='Основная подкатегория')
    name = models.CharField('Название подкатегории', max_length=255, blank=False, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField('Изображение подкатегории', upload_to='sub_category_img/', blank=True)
    page_title = models.CharField('Название страницы SEO', max_length=255, blank=True, null=True)
    page_description = models.CharField('Описание страницы SEO', max_length=255, blank=True, null=True)
    page_keywords = models.TextField('Keywords SEO', blank=True, null=True)
    description = RichTextUploadingField('Описание подкатегории', blank=True, null=True)
    short_description = models.TextField('Краткое описание', blank=True)
    discount = models.IntegerField('Скидка на все товары в подкатегории %', blank=True, default=0)
    views = models.IntegerField('Просмотров', default=0)
    is_active = models.BooleanField('Отображать подкатегорию ?', default=True, db_index=True)
    subsubcat_id = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        slug = slugify(self.name)
        print(slug)
        testSlug = SubSubCategory.objects.filter(name_slug=slug)
        print(testSlug)
        slugRandom = ''
        if not self.name_slug or testSlug:
            if testSlug:
                slugRandom = '-' + ''.join(choices(string.ascii_lowercase + string.digits, k=2))
                self.name_slug = slug + slugRandom
            else:
                self.name_slug = slug
        self.name_lower = self.name.lower()
        # all_items = self.item_set.all()
        # for item in all_items:
        #     item.discount = self.discount
        #     item.save()



        # all_items = self.item_set.all()
        # for item in all_items:
        #     item.discount = self.discount
        #     item.save()

        super(SubSubCategory, self).save(*args, **kwargs)

    def __str__(self):
        return '%s ' % self.name

    class Meta:
        verbose_name = "Подкатегория"
        verbose_name_plural = "Подкатегории"


class Filter(models.Model):
    subcategory = models.ForeignKey(SubSubCategory, blank=True, null=True, on_delete=models.SET_NULL,
                                    verbose_name='Подкатегория')
    name = models.CharField('Фильтр', max_length=255, blank=False, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        slug = slugify(self.name)
        testSlug = Item.objects.filter(name_slug=slug)
        slugRandom = ''
        if self.name_slug != slug:
            if testSlug:
                slugRandom = '-' + ''.join(choices(string.ascii_lowercase + string.digits, k=2))
                self.name_slug = slug + slugRandom
            else:
                self.name_slug = slug
        self.name_lower = self.name.lower()
        super(Filter, self).save(*args, **kwargs)

    def __str__(self):
        return 'Фильтр %s для подкатегории %s ' % (self.name, self.subcategory.name)

    class Meta:
        verbose_name = "Фильтр"
        verbose_name_plural = "Фильтры"


class Item(models.Model):
    subcategory = models.ManyToManyField(SubSubCategory, blank=True, verbose_name='Подкатегория', db_index=True, related_name='subsubcategory')
    filter = models.ForeignKey(Filter, blank=True, null=True, on_delete=models.SET_NULL, db_index=True,
                               verbose_name='Фильтр')
    name = models.CharField('Название товара', max_length=255, blank=False, null=True)
    name_lower = models.CharField(max_length=255, blank=True, null=True, default='')
    name_slug = models.CharField(max_length=255, blank=True, null=True, db_index=True)

    page_title = models.CharField('Название страницы SEO', max_length=255, blank=True, null=True)
    page_description = models.TextField('Описание страницы SEO', blank=True, null=True)
    page_keywords = models.TextField('Keywords SEO', blank=True, null=True)
    description = RichTextUploadingField('Описание товара (отображается на странице товара)', blank=True, null=True)
    short_description = models.TextField(
        'Краткое описание товара (отображается в карточке товара)',
        blank=True, null=True)

    good_time = models.CharField('Срок годности', max_length=15, default='1 год')
    weight = models.CharField('Вес', max_length=15, default='не указано')
    ph = models.CharField('pH', max_length=15, blank=True, default='0')
    fasovka = models.CharField('Фасовка', max_length=50, blank=True, null=True, default='не указано')
    zapah = models.CharField('Запах', max_length=50, blank=True, null=True, default='не указано')
    is_active = models.BooleanField('Отображать товар ?', default=True, db_index=True)
    is_present = models.BooleanField('Товар в наличии ?', default=True, db_index=True)
    item_idd = models.IntegerField(default=0)
    buys = models.IntegerField('Покупок', default=0)
    views = models.IntegerField('Просмотров', default=0)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        print('save')
        slug = slugify(self.name)
        testSlug = Item.objects.filter(name_slug=slug)
        slugRandom = ''
        if self.name_slug != slug:
            if testSlug:
                slugRandom = '-' + ''.join(choices(string.ascii_lowercase + string.digits, k=2))
                self.name_slug = slug + slugRandom
            else:
                self.name_slug = slug
        self.name_lower = self.name.lower()

templates/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <meta name="description" content="{{ description }}" />
    <meta name="keywords" content="{{ keywords }}" />
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/amaran.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/showLoading.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css'%}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<form id="dummy_form">{% csrf_token %}</form>
{% block content %}
{% endblock %}
{% include 'footer.html' %}

<script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/jquery.amaran.min.js' %}"></script>
<script src="{% static 'js/add_to_cart.js' %}"></script>
<script src="{% static 'js/delete_from_cart.js' %}"></script>
<script src="{% static 'js/login.js' %}"></script>

{% block js %}
  <script>
    /***
     * открываем подкатегорию в мобильном меню
     **/
    function openSubcategory(el){
        console.log(el)
        let allSubCats = document.getElementsByClassName('mobile-sub-categories-wrapper')
        for (x of allSubCats){
            x.classList.remove('sub-active')
        }
        el.classList.add('sub-active')
    }
    /***
     * открываем категорию в мобильном меню
     **/
    function openCategory(el){
        console.log(el)

        let allCats = document.getElementsByClassName('mobile-main-categories-wrapper')
        for (x of allCats){
            x.classList.remove('main-active')
        }

        el.classList.add('main-active')
    }
    /***
     * открываем и закрываем мобильное меню
     **/
    function toggleMenu() {
        let menu = document.getElementsByClassName('header-mobile-menu')[0]
        menu.classList.toggle('mobile-menu-active')
    }
</script>
<script>
    /***
     *
     * открываем и закрываем меню корзины
     */
    let cart = document.getElementById("shopping-bag");
    let cart_menu = document.getElementById("shopping_bag_menu");
    function showcart() {
        console.log('enter')
        cart_menu.style.display = 'block'
        cart_menu.classList.add('slide-top')

    }
    function hidecart() {
        cart_menu.style.display = 'none'

    }
    cart.addEventListener("mouseenter", showcart, false);
    cart_menu.addEventListener("mouseleave", hidecart, false)
</script>
<script>
    /**
     * каталог товаров
     */
    let menu_items = document.getElementsByClassName('categories-nav-item')
    let menu_items_link = document.getElementsByClassName('categories-nav-item-link')
    let sub_menus = document.getElementsByClassName('categories-nav-dropdown')
    let menu_id = ''
    let li_id = ''
    console.log( menu_items)

    for (var i = 0; i < menu_items.length; i++){
        menu_items[i].addEventListener("mouseover", function( event ) {
            menu_id = event.target.dataset.menu_id
            li_id = event.target.dataset.li_id
            let menu = document.getElementById('menu_id_'+menu_id)
            menu.classList.add('menu-active')
            event.target.classList.add('hover')
            console.log(menu)
        })
    }

    for (var i = 0; i < menu_items.length; i++){
        menu_items[i].addEventListener("mouseout", function( event ) {
            event.target.classList.remove('hover')
            let menu = document.getElementById('menu_id_'+menu_id)
            console.log('related= '+ (event.relatedTarget.classList))
            if (event.relatedTarget.classList != 'categories-nav-dropdown menu-active'){
                console.log('close')
                menu.classList.remove('menu-active')
            }else{
                console.log('not close')
                let li = document.getElementById('li_id_'+menu_id)
                li.classList.add('li-before')
            }
        })
    }
    for (var i = 0; i < sub_menus.length; i++){
        sub_menus[i].addEventListener("mouseover", function( event ) {
            console.log('menu over')
            let li = document.getElementById('li_id_'+menu_id)
            li.classList.add('hover')


        })
    }
    for (var i = 0; i < sub_menus.length; i++){
        sub_menus[i].addEventListener("mouseleave", function( event ) {
            console.log('menu out')
            let li = document.getElementById('li_id_'+menu_id)
            li.classList.remove('hover')
            let menu = document.getElementById('menu_id_'+menu_id)
            menu.classList.remove('menu-active')
            li.classList.remove('li-before')
        })
    }
</script>
{% endblock %}
</body>
</html>

templates/blank.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}

{% endblock %}

{% block js %}
{% endblock %}

templates/header_grey.html
<header class="header bg-gray" >
  {% include 'header_inner.html' %}

</header>

templates/header_inner.html
<div class="container hidden-md">
    <div class="header-top">
        <ul>
            <li><a href="#">Краснодар</a></li>
            <li><a href="#">Информация о доставке</a></li>
            <li><a href="#">Бонусная программа</a></li>
            <li><a href="#">Частые вопросы</a></li>
        </ul>
    </div>
    <div class="header-inner">
        <a href="{% url 'index' %}">
            <img src="http://placehold.it/300x70" alt="">
        </a>


        <form class="search-form">
            <input class="search-input" name="search-query" placeholder="Поиск товаров по сайту" required>
            <button class="search-input-button" type="submit"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                                                   width="24" height="24"
                                                                   viewBox="0 0 24 24"
                                                                   style=" fill:#44d4de;">    <path d="M 9 2 C 5.1458514 2 2 5.1458514 2 9 C 2 12.854149 5.1458514 16 9 16 C 10.747998 16 12.345009 15.348024 13.574219 14.28125 L 14 14.707031 L 14 16 L 20 22 L 22 20 L 16 14 L 14.707031 14 L 14.28125 13.574219 C 15.348024 12.345009 16 10.747998 16 9 C 16 5.1458514 12.854149 2 9 2 z M 9 4 C 11.773268 4 14 6.2267316 14 9 C 14 11.773268 11.773268 14 9 14 C 6.2267316 14 4 11.773268 4 9 C 4 6.2267316 6.2267316 4 9 4 z"></path></svg></button>
        </form>

        <div class="header-icons-block">
            <div  class="header-cart">
                {% if request.user.is_authenticated %}

                    <a  href="#"><span class="user-lk"><!--span class="cart-items">!</span--></span></a>
                {% else %}
                    <a  href="javascript:void(0)" onclick="openUserModal()"><span class="user-lk"><!--span class="cart-items">!</span--></span></a>
                {% endif %}

            </div>
            <div id="shopping-bag" class="header-cart">
                <a  href="#"><span class="shopping-bag">
                        {% if count_items_in_cart > 0 %}
                            <span class="cart-items">{{ count_items_in_cart }}</span>
                        {% else %}
                            <span style="display: none" class="cart-items"></span>
                        {% endif %}
                    </span></a>
                <div id="shopping_bag_menu" class="menu-cart-items">

                    <table class="cart_table">
                        {% for cart_item in all_items_in_cart %}
                            <tr>
                                <td >
                                    <img  src="{{ cart_item.item.item.itemimage_set.first.image_small }}" alt="">
                                </td>
                                <td>
                                    {{ cart_item.item.item.name }} {{ cart_item.item.volume}} {{ cart_item.item.unit }}
                                </td>
                                <td>
                                    <span id="cart_item_number">{{ cart_item.number }}</span> x  <span id="cart_item_price">{{ cart_item.current_price }} &#8381;</span> = <span id="cart_item_total_price">{{ cart_item.total_price  }} &#8381;</span>
                                </td>
                                <td>
                                    <a class="cart-delete-btn" href="javascript:void(0)"
                                       data-item_id="{{ cart_item.id }}"
                                       onclick="delete_from_cart(this)"><span>&#10006;</span></a>
                                </td>
                            </tr>
                        {% endfor %}
                        {% if count_items_in_cart > 0 %}
                            <tr class="cart-footer">
                                <td colspan="4">Итого: {{ total_cart_price }} &#8381;</td>
                            </tr>
                            <tr>
                                <td colspan="4">
                                    <a href="{% url 'show_cart' %}" class="btn btn-sm">Открыть корзину</a>
                                    <a href="{% url 'checkout' %}" class="btn-outline btn-sm">Оплата</a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td style="width: 100% !important;"> Корзина пуста</td>
                            </tr>
                        {% endif %}
                    </table>

                </div>
            </div>

        </div>


    </div>
    <div class="categories-nav">
        {% for category in all_categories %}
            <ul>
                <li class="categories-nav-item" id="li_id_{{ category.id }}" data-menu_id="{{ category.id }}"><a class="categories-nav-item-link" href="{% url 'category' category.name_slug%}">{{ category.name }}</a></li>

            </ul>
        {% endfor %}
    </div>

    {% for category in all_categories %}
        <div id="menu_id_{{ category.id }}" data-li_id="{{ category.id }}" class="categories-nav-dropdown" >

            {% for subcat in category.subcategory_set.all %}
                <ul class="categories-nav-dropdown-subcategory-items">

                    <li><a href="{% url 'subcategory' category.name_slug subcat.name_slug %}">{{ subcat.name }}</a></li>

                    {% for subsubcat in subcat.subsubcategory_set.all %}
                        <li><a href="{% url 'subsubcategory' category.name_slug subcat.name_slug subsubcat.name_slug %}">{{ subsubcat.name }}</a></li>
                    {% endfor %}

                </ul>
            {% endfor %}
        </div>
    {% endfor %}


</div>
<div class="mobile-header container visible-md">


    <div class="header-mobile-close">
        <a>
            <img src="http://placehold.it/300x70" alt="">
        </a>
        <span onclick="toggleMenu()">&#9776;</span>
    </div>

</div>
<div class="header-mobile-menu">
    <div class="header-mobile-menu-top">
        <div class="header-mobile-close">
            <p>телефон</p>
            <span onclick="toggleMenu()">&#10006;</span>
        </div>
        <ul>
            <li><a href="#">Краснодар</a></li>
            <li><a href="#">Информация о доставке</a></li>
            <li><a href="#">Бонусная программа</a></li>
            <li><a href="#">Частые вопросы</a></li>
            <li><a href="#">Вход/Регистрация</a></li>
            <li><a href="#">Корзина</a></li>
        </ul>
    </div>

    <form class="search-form">
        <input class="search-input" name="search-query" placeholder="Поиск товаров по сайту" required>
        <button class="search-input-button" type="submit"><svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"
                                                               width="24" height="24"
                                                               viewBox="0 0 24 24"
                                                               style=" fill:#44d4de;">    <path d="M 9 2 C 5.1458514 2 2 5.1458514 2 9 C 2 12.854149 5.1458514 16 9 16 C 10.747998 16 12.345009 15.348024 13.574219 14.28125 L 14 14.707031 L 14 16 L 20 22 L 22 20 L 16 14 L 14.707031 14 L 14.28125 13.574219 C 15.348024 12.345009 16 10.747998 16 9 C 16 5.1458514 12.854149 2 9 2 z M 9 4 C 11.773268 4 14 6.2267316 14 9 C 14 11.773268 11.773268 14 9 14 C 6.2267316 14 4 11.773268 4 9 C 4 6.2267316 6.2267316 4 9 4 z"></path></svg></button>
    </form>

    <ul class="mobile-main-categories">
        {% for category in all_categories %}
            <li class="mobile-main-categories-wrapper " onclick="openCategory(this)">
                <a class="mobile-main-categories-item" href="#">{{ category.name }}</a>
                {% for subcat in category.subcategory_set.all %}
                    <ul class="mobile-sub-categories">
                        <li class="mobile-sub-categories-wrapper"  onclick="openSubcategory(this)">
                            <a class="mobile-sub-categories-item" href="#">{{ subcat.name }}</a>
                            <ul class="mobile-subsub-categories">
                                {% for subsubcat in subcat.subsubcategory_set.all %}
                                    <li><a class="mobile-subsub-categories-item" href="{% url 'subsubcategory' category.name_slug subcat.name_slug subsubcat.name_slug %}">{{ subsubcat.name }}</a> </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                {% endfor %}
            </li>
        {% endfor %}

    </ul>

</div>

templates/header_white.html
<header class="header">
  {% include 'header_inner.html' %}

</header>